### ISSUE TITLE
slim serve static files

### ISSUE THREAD

**Issue by zmwebdev** [zmwebdev/php-examples#30]
render?
redirect?
CSS, HTML

https://github.com/ieraielizondo/trackingapp/tree/trackingapp_Slim

http://willisbored.com/2011/04/04/tutorial-slim-php-view-templates/

**Comment by zmwebdev** [comment]
Use twig inside slim

https://github.com/zmwebdev/php-examples/tree/master/08-templating/twig

**Comment by zmwebdev** [comment]
https://github.com/zmwebdev/php-examples/tree/master/11-RESTful-API/slim/03-slim-twig

**Comment by ieraielizondo** [comment]
##Solución:
$app->redirect($app->urlFor('NombreRuta'));
Y hacer $app->render('xxxxxxxx.php');
:ok_hand:
